//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> MajorID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> ProfessorID { get; set; }
    }
}
